source 'http://rubygems.org'

gem 'rails', '3.2.12'

group :assets do
  gem 'asset_sync', '0.5.0'
  gem 'bootstrap-sass-rails', '2.3.1.0'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'compass-rails', '1.0.3'
  gem 'font-awesome-sass-rails', '3.0.2.2'
  gem 'less-rails', '2.2.6'
  gem 'sass-rails',   '~> 3.2.3'
  gem 'uglifier', '>= 1.0.3'
end

#gem 'bartt-ssl_requirement', '~> 1.4.0', require: 'ssl_requirement'
gem 'bootstrap-will_paginate', '0.0.9'
gem 'cancan', '1.6.8'
gem 'carrierwave', '0.7.1'
gem 'country-select', '1.1.1'
gem 'dalli', '2.5.0'  # memcached
gem 'devise', '2.1.2'
gem 'draper', '1.0.0.beta3'
gem 'fog', '1.7.0'
gem 'haml', '3.1.7'
gem 'haml-rails', '0.3.5'
gem 'heroku-api', '0.3.7'
gem 'hpricot', '0.8.6'
#gem 'i18n_country_select', '1.0.16'
gem 'jquery-rails', '2.1.4'
gem 'jquery-ui-rails', '2.0.0'
#gem 'mailboxer', '0.9.0'
gem 'nested_form', '0.3.1'
gem 'newrelic_rpm', '3.5.2.17'
gem 'nokogiri', '~> 1.5.5'
#gem 'omniauth-facebook', '1.4.0', require: 'omniauth-facebook'
#gem 'omniauth-linkedin', '0.0.8'
#gem 'omniauth-oauth', '1.0.1'  # for omniauth-twitter
#gem 'omniauth-oauth2', '1.0.3'  # for omniauth-facebook
#gem 'omniauth-twitter', '0.0.14'
gem 'pg', '~> 0.14.1'
gem 'premailer-rails3', '1.3.1'
gem 'redcarpet', '2.2.2'
gem 'redis', '3.0.2'
#gem 'redis-namespace', '1.2.1'
gem 'resque', '1.23.0', require: 'resque/server'
gem 'resque-scheduler', '2.0.0', require: 'resque_scheduler'
gem 'rmagick', '2.13.1'
gem 'rubyzip', '0.9.9'
gem 'sanitize', '2.0.3'
gem 'sendgrid', '1.1.0'
gem 'simple_form', '2.0.4'
gem 'skeleton-rails', '0.0.2'
gem 'sundawg_country_codes', '0.0.7'
gem 'text_sanitizer', '0.0.2'
gem 'tire', '0.5.5'
gem 'therubyracer', '0.10.2'
gem 'twitter-bootstrap-rails', '2.2.6'
gem 'unicorn', '4.4.0'
gem 'vimeo', '1.5.3'
gem 'will_paginate', '3.0.4'
gem 'workflow', '0.8.1'
gem 'wysihtml5-rails', '0.0.4'

group :development, :test do
  gem 'capybara'
  gem 'factory_girl_rails'
  gem 'foreman'
  gem 'guard-livereload'
  gem 'guard-rspec'
  gem 'guard-spork'
  gem 'launchy'
  gem 'spork'
  gem 'rb-inotify'
  gem 'rspec-cells'
  gem 'rspec-rails'
  gem 'sqlite3'
end

group :test do
  gem 'database_cleaner'
  gem 'faker'
end