development:
  host: localhost
  port: 6379
  login:
  password:
staging:
  host: hoki.redistogo.com
  port: 9133
  login: redistogo
  password: e94e0d33cc5c54f51c5471d9e96036dd
production:
  host: cod.redistogo.com
  port: 9516
  login: redistogo
  password: 9b6a4480f7245c334a9cb3f8a1226d4d