microsoft:
  prefix: 'ms_chrome'
  default_locale: 'en'
  attributes:
    - !ruby/symbol chrome_footer
    - !ruby/symbol chrome_header
cypress:
  prefix: 'cy_chrome'
  default_locale: 'en'
  attributes:
    - !ruby/symbol chrome_footer
    - !ruby/symbol chrome_header
    - !ruby/symbol head
    - !ruby/symbol js
chip:
  prefix: 'chip_chrome'
  default_locale: 'en'
  attributes:
    - !ruby/symbol header
    - !ruby/symbol footer
    - !ruby/symbol head
    - !ruby/symbol js