microsoft:
  prefix: 'ms_chrome'
  default_locale: 'en'
  attributes:
    - !ruby/symbol chrome_footer
    - !ruby/symbol chrome_header
    - !ruby/symbol nav
    - !ruby/symbol nav_css
cypress:
  prefix: 'cy_sync'
  default_locale: 'en'
  attributes:
    - !ruby/symbol chrome_footer
    - !ruby/symbol chrome_header