development:
  full_host: www.localhost.local:5000
  default_host: www.localhost.local
  default_domain: localhost.local
  default_port: 5000
  send_emails: false
  workers_running: false
  purging_enable: false
  stats_url: www.localhost.local:5000
  use_ssl: false

# development:
#   full_host: www.lvh.me:5000
#   default_host: www.lvh.me
#   default_domain: lvh.me
#   default_port: 5000
#   send_emails: false

test:
  full_host: www.example.com
  default_host: www.example.com
  default_domain: example.com
  default_port: 80
  send_emails: false
  workers_running: false
  purging_enable: false
  stats_url: www.localhost.local:5000
  use_ssl: false

staging:
  full_host: staging.hackster.io
  default_host: staging.hackster.io
  default_domain: hackster.io
  default_port: 80
  send_emails: true
  workers_running: false
  purging_enable: false
  stats_url: staging.hackster.io
  use_ssl: false

dev:
  full_host: dev.hackster.io
  default_host: dev.hackster.io
  default_domain: hackster.io
  default_port: 80
  send_emails: true
  workers_running: true
  purging_enable: true
  stats_url: dev.hackster.io
  use_ssl: true

production:
  full_host: www.hackster.io
  default_host: www.hackster.io
  default_domain: hackster.io
  default_port: 80
  send_emails: true
  workers_running: true
  purging_enable: true
  stats_url: stats.hackster.io
  use_ssl: true

stats:
  full_host: stats.hackster.io
  default_host: stats.hackster.io
  default_domain: hackster.io
  default_port: 80
  send_emails: true
  workers_running: true
  purging_enable: true
  stats_url: stats.hackster.io
  use_ssl: true