development:
  full_host: www.localhost.local:5000
  default_host: www.localhost.local
  default_domain: localhost.local
  default_port: 5000
  send_emails: false

# development:
#   full_host: www.lvh.me:5000
#   default_host: www.lvh.me
#   default_domain: lvh.me
#   default_port: 5000
#   send_emails: false

test:
  full_host: www.example.com
  default_host: www.example.com
  default_domain: example.com
  default_port: 80
  send_emails: false

staging:
  full_host: staging.hackster.io
  default_host: staging.hackster.io
  default_domain: hackster.io
  default_port: 80
  send_emails: true

dev:
  full_host: dev.hackster.io
  default_host: dev.hackster.io
  default_domain: hackster.io
  default_port: 80
  send_emails: true

production:
  full_host: www.hackster.io
  default_host: www.hackster.io
  default_domain: hackster.io
  default_port: 80
  send_emails: true