development:
  full_host: www.localhost.local:5000
  default_host: www.localhost.local
  default_port: 5000
  send_emails: false

test:
  full_host: www.example.com
  default_host: www.example.com
  default_port: 80
  send_emails: false

production:
  full_host: www.hackster.io
  default_host: www.hackster.io
  default_port: 80
  send_emails: true