development:
  full_host: beta.lvh.me:5000
  default_host: beta.lvh.me
  default_port: 5000
  send_emails: false

test:
  full_host: www.example.com
  default_host: www.example.com
  default_port: 80
  send_emails: false

production:
  full_host: beta.hackster.io
  default_host: beta.hackster.io
  default_port: 80
  send_emails: true