minutely:
  cron: "* * * * *"
  class: "CriticalCronWorker"
  args:
    - launch_cron

hourly:
  cron: "0 * * * *"
  class: "CronTask"
  args:
    - launch_cron

daily:
  cron: "0 5 * * *"
  class: "CronTask"
  args:
    - launch_daily_cron

weekly:
  cron: "0 17 * * 1"
  class: "CronTask"
  args:
    - launch_weekly_cron