production:
  site.baseurl: "http://ms-iot.github.io/content"
  site.repository_url: "https://github.com/ms-iot/content/blob/develop/"
  site.landingurl: "http://dev.windows.com/iot"
  site.hacksterurl: "http://microsoft.hackster.io"
  site.hardwareurl: "http://go.microsoft.com/fwlink/p/?linkID=532948"
  site.signupurl: "https://www.windowsondevices.com/signup.aspx"

development:
  site.baseurl: "https://content-private.azurewebsites.net/content"
  site.repository_url: "https://github.com/ms-iot/content-private/blob/develop/"
  site.landingurl: "http://devx.windows-int.com/iot"
  site.hacksterurl: "http://microsoft.localhost.local:5000"
  site.hardwareurl: "http://go.microsoft.com/fwlink/p/?linkID=532948"
  site.signupurl: "https://www.windowsondevices.com/signup.aspx"