phases:
  :0:
    :date: 01-05-2016
    :event: Project submissions open
  :1:
    :date: 15-05-2016
    :event: Project submissions close
    :sub_event: Preliminary voting begins
  :2:
    :date: 15-05-2016
    :event: Preliminary voting begins
  :3:
    :date: 31-05-2016
    :event: Project voting ends
    :sub_event: Vendor champions chosen
  :4:
    :date: 01-06-2016
    :event: Round 1 begins
  :5:
    :date: 10-06-2016
    :event: Round 2 begins
  :6:
    :date: 20-06-2016
    :event: Round 3 begins
  :7:
    :date: 30-06-2016
    :event: Competition ends
    :sub_event: Winner announced