development:
  secret_key_base: 28a9858be6ce05d24b3eb312aea065ecdab732883ab5d280118fabebcbbf56269009aa115b4713f2da7a09eb57be9278d96a1e931250235d29d84b667001b1e7
staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
dev:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>