promise_20150820:
  alternatives:
    - build
    - learn
    - share
  metadata:
    build:
      text: 'Hackster is the place where hardware gets created. Learn, share and connect to build better hardware.'
      link_text: 'Learn more.'
      link_url: '/about'
    learn:
      text: 'Hackster is a community of people who learn and teach each other how to create hardware.'
      link_text: 'Browse tutorials.'
      link_url: '/projects'
    share:
      text: 'Hackster is a community dedicated to sharing open-source hardware projects.'
      link_text: 'Browse projects.'
      link_url: '/projects'
  resettable: false
  goals:
    - signup
    # - click_link

promise_20150821:
  alternatives:
    # control:
    - 'Learn, share and connect to build better hardware.'
    # learn:
    - 'Learn from others and find thousands of instructions for your next hardware projects.'
    # connect:
    - 'Connect with thousands of other hardware enthusiasts around the world.'
    # collaborate:
    - 'Find collaborators for your next hardware projects or join existing ones.'
    # share:
    - 'Share your open-source hardware projects and get inspiration from thousands of others.'
    # earn:
    - 'Earn money and prizes while building hardware.'
    # help:
    # - 'Receive support and feedback for your hardware projects.'
    - 'Get help building your hardware projects.'
  resettable: false